/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package love;

import javax.swing.ImageIcon;

/**
 *
 * @author Joaquin Navarro
 */
public class Frame extends javax.swing.JFrame {
    int x, y;
    public Frame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnSi = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(601, 339));
        setMinimumSize(new java.awt.Dimension(601, 339));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 339));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abel\\Documents\\NetBeansProjects\\Love\\imagenes\\salida.png")); // NOI18N
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                salirMouseMoved(evt);
            }
        });
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 40, 40));

        btnNo.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abel\\Documents\\NetBeansProjects\\Love\\imagenes\\cerrar.png")); // NOI18N
        btnNo.setText("No");
        btnNo.setBorder(null);
        btnNo.setBorderPainted(false);
        btnNo.setContentAreaFilled(false);
        btnNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNo.setFocusPainted(false);
        btnNo.setFocusable(false);
        btnNo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNoMouseMoved(evt);
            }
        });
        getContentPane().add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, -1));

        lblTitulo.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("¿Quieres ser mi Novia?");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        btnSi.setFont(new java.awt.Font("Decker", 1, 14)); // NOI18N
        btnSi.setForeground(new java.awt.Color(255, 255, 255));
        btnSi.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abel\\Documents\\NetBeansProjects\\Love\\imagenes\\corazon (1).png")); // NOI18N
        btnSi.setText("Si");
        btnSi.setBorder(null);
        btnSi.setBorderPainted(false);
        btnSi.setContentAreaFilled(false);
        btnSi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSi.setFocusPainted(false);
        btnSi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSiMouseMoved(evt);
            }
        });
        btnSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiMouseExited(evt);
            }
        });
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        getContentPane().add(btnSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 60, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Abel\\Documents\\NetBeansProjects\\Love\\imagenes\\fondo.jpg")); // NOI18N
        lblFondo.setMaximumSize(new java.awt.Dimension(600, 338));
        lblFondo.setMinimumSize(new java.awt.Dimension(600, 338));
        lblFondo.setPreferredSize(new java.awt.Dimension(600, 338));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 338));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseMoved
        ImageIcon img = new ImageIcon("imagenes/salidaONN.png");
        salir.setIcon(img);
    }//GEN-LAST:event_salirMouseMoved

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        ImageIcon img = new ImageIcon("imagenes/salida.png");
        salir.setIcon(img);
    }//GEN-LAST:event_salirMouseExited

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(1);
    }//GEN-LAST:event_salirMouseClicked

    private void btnSiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseMoved
        ImageIcon img = new ImageIcon("imagenes/corazon.png");
        btnSi.setIcon(img);
    }//GEN-LAST:event_btnSiMouseMoved

    private void btnSiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiMouseExited
        ImageIcon img = new ImageIcon("imagenes/corazon1.png");
        btnSi.setIcon(img);
    }//GEN-LAST:event_btnSiMouseExited

    private void btnNoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseMoved
        x = (int) (Math.random()*540 + 0);
        y = (int) (Math.random()*306 + 0);
        btnNo.setBounds(x, y, 60, 32);
    }//GEN-LAST:event_btnNoMouseMoved

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        new Exito().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
